---
- hosts: localhost
  roles:
    - role: andrewrothstein.pkg-upgrade
    - role: andrewrothstein.supervisord
    - role: andrewrothstein.jupyter-supervisord
      jupyter_profile_config_options:
        - key : NotebookApp.base_url
          value: "'/'"
        - key: NotebookApp.ip
          value: "'*'"
        - key: NotebookApp.token
          value: "''"


